version: '3'

services:
  client:
    build: .
    image: jgkapp24/spot-a-fly-header:latest
    depends_on:
      - 'cache'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=prod

  cache:
    image: redis

